import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { useRouter } from "next/router";
import { signOut, useSession } from "next-auth/react";

import { api } from "~/utils/api";
import clsx from "clsx";

const Home: NextPage = () => {
  const router = useRouter();

  const { data: session } = useSession();

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <nav className="flex items-center justify-between border-b border-gray-200 px-6 py-3">
        <div className="flex gap-6">
          <p className="font-extrabold text-gray-800">NextJS Starter</p>

          <ul>
            <li>
              <Link href="/" className="hover:underline">
                Home
              </Link>
            </li>
          </ul>
        </div>

        <div className="flex items-center gap-4 text-gray-600">
          <p className={clsx(!session ? "hidden" : null)}>
            Hello, {session && session.user?.email}
          </p>
          <button
            className="rounded-md bg-indigo-500 px-6 py-2 font-medium text-white hover:bg-indigo-700"
            onClick={
              session ? () => void signOut() : () => void router.push("/login")
            }
          >
            {session ? "Logout" : "Login"}
          </button>
        </div>
      </nav>

      <main className="mt-32 flex flex-col items-center justify-center gap-6">
        <h1 className="text-5xl font-bold text-slate-800">
          NextJS Starter Template
        </h1>
        <p className="text-md text-slate-500">
          NextJS + Tailwind CSS + tRPC + NextAuth.js starter template
        </p>
      </main>
    </>
  );
};

export default Home;
